[package]
name = "aa"
version = "0.3.0"
authors = ["Richard Mills <scripts.richard@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
ctrlc = "3.1.2"
slog = "2.4.1"
slog-async = "2.3.0"
slog-term = "2.4.0"
walkdir = "2"
inotify = "0.7"
